services:
  - type: web
    name: gym-apes-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: APP_URL
        sync: false