services:
  - type: web
    name: gym-apes-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT bot:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: APP_URL
        sync: false
      - key: GIST_TOKEN
        sync: false
      - key: GIST_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
